kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"cs-rest-backend","version":"v1"},"name":"cs-node-rest-backend","namespace":"tekton-pipelines"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"cs-rest-backend","version":"v1"}},"template":{"metadata":{"labels":{"app":"cs-rest-backend","version":"v1"}},"spec":{"containers":[{"image":"image-registry.openshift-image-registry.svc:5000/tekton-pipelines/cs-rest-backend:v1","imagePullPolicy":"Always","name":"cs-rest-app","ports":[{"containerPort":9000,"protocol":"TCP"}],"resources":{}}],"restartPolicy":"Always"}}}}
  name: cs-node-rest-backend
  namespace: tekton-pipelines
  labels:
    app: cs-rest-backend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs-rest-backend
      version: v1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cs-rest-backend
        version: v1
    spec:
      containers:
        - name: cs-rest-app
          image: >-
            image-registry.openshift-image-registry.svc:5000/tekton-pipelines/cs-rest-backend:v1
          ports:
            - containerPort: 9000
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2020-07-14T20:37:48Z'
      lastTransitionTime: '2020-07-14T20:37:48Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2020-07-14T20:37:48Z'
      lastTransitionTime: '2020-07-14T20:37:42Z'
      reason: NewReplicaSetAvailable
      message: >-
        ReplicaSet "cs-node-rest-backend-6776fd66ff" has successfully
        progressed.