apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: cs-rest-backend-route
  namespace: tekton-pipelines
spec:
  steps:
    - image: 'quay.io/openshift/origin-cli:latest'
      name: oc
      resources: {}
      script: |
        oc delete route cs-rest-route -n tekton-pipelines
        cat << EOF | kubectl apply -n tekton-pipelines -f - 
        kind: Route
        apiVersion: route.openshift.io/v1
        metadata:
          name: cs-rest-route
          namespace: tekton-pipelines
        spec:
          path: /
          to:
            kind: Service
            name: cs-rest-service
          port:
            targetPort: 9000
        EOF