apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: cs-rest-backend
  namespace: tekton-pipelines
spec:
  params:
    - name: url
      value: 'https://github.com/csamarchi/Restaraunt-Backend'
    - name: revision
      value: master
  type: git