apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: cs-rest-image
  namespace: tekton-pipelines
spec:
  params:
    - name: url
      value: >-
        image-registry.openshift-image-registry.svc:5000/tekton-pipelines/cs-rest-backend
  type: image